FROM python:3.8.16-slim

#COPY . /app

# COPY requirements.txt /app/requirements.txt

WORKDIR /app/

RUN apt-get clean && \
    apt-get update && \
    apt-get install -y --no-install-recommends gcc mono-mcs \
    build-essential libopenmpi-dev && \
    python3

#RUN python3 -m venv /opt/venv && \
 #   /opt/venv/bin/python -m pip install pip --upgrade && \
  #  /opt/venv/bin/python -m pip install -r /app/src/requirements.txt

# purge unused
RUN apt-get remove -y --purge make gcc build-essential &&\
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

RUN chmod +x ./src/entrypoint.sh

CMD [ "./src/entrypoint.sh" ]
