
name: CI Workflow

on:
  # Allows manual triggering with a folder name prompt
  workflow_dispatch:
    inputs:
      dockerfile_folder:
        description: "Enter the folder name where Dockerfile is located"
        required: true
        default: " "

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        # Uses the folder name input to locate the Dockerfile
        run: docker build -t my-tomcat-image -f ${{ github.event.inputs.dockerfile_folder }}/Dockerfile ${{ github.event.inputs.dockerfile_folder }}

      - name: Run Docker container
        run: docker run my-tomcat-image
