
name: CI Workflow

on:
  # Allows manual triggering with a folder name prompt
  workflow_dispatch:
    inputs:
      dockerfile_folder:
        description: "Enter the folder name where Dockerfile is located"
        required: true
        default: " "
      tag_name:
        description: "Enter tag name"
        required: true
        default: " "
      image_name:
        description: "Enter image name"
        required: true
         default: " "
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        # Uses the folder name input to locate the Dockerfile
        run: docker build -t  rajeshnimmana/dockerbuild -f ${{ github.event.inputs.dockerfile_folder }}/Dockerfile ${{ github.event.inputs.dockerfile_folder }}
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: push to Docker hub
        run: docker push rajeshnimmana/${{ github.event.inputs.image_name }}:${{ github.event.inputs.tag_name }}
        
#      - name: Run Docker container
 #       run: docker run my-tomcat-image
